services:
    
    motherbrain_product_subcription_plugin.form.type.plan:
        class: Motherbrain\SyliusProductSubscriptionPlugin\Form\Type\PlanType
        arguments:
            - '%motherbrain_sylius_product_subscription_plugin.model.plan.class%'
            - []
        tags:
            - { name: form.type }

    motherbrain_product_subcription_plugin.form.type.plan_translation:
        class: Motherbrain\SyliusProductSubscriptionPlugin\Form\Type\PlanTranslationType
        arguments:
            - '%motherbrain_sylius_product_subscription_plugin.model.plan_translation.class%'
            - []
        tags:
            - { name: form.type }
        
    motherbrain_product_subscription_plugin.form.type.plan_gateway_config:
        class: Motherbrain\SyliusProductSubscriptionPlugin\Form\Type\PlanGatewayConfigType
        arguments:
            - '%motherbrain_sylius_product_subscription_plugin.model.plan_gateway_config.class%'
            - []
            - '@motherbrain_product_subscription_plugin.form_registry.plan_config'
        tags:
            - { name: form.type }            
        
