#Motherbrain\SyliusProductSubscriptionPlugin\ApiPlatform\Command\SelectPlan:
#    constraints:
#        - Sylius\Bundle\ApiBundle\Validator\Constraints\CorrectOrderAddress:
#              groups: [ 'sylius' ]
